#!/bin/bash
# scripts/pi-cd-install.sh
#
# One-command activation for the pull-based CI/CD pipeline on the Pi.
# Run once on the Pi (with sudo) after this commit lands in /opt/tradewiser.
#
#   sudo /opt/tradewiser/scripts/pi-cd-install.sh
#
# What it does (all idempotent — safe to re-run):
#   1. Makes pi-deploy.sh executable.
#   2. Writes /etc/sudoers.d/tradewiser-deploy so the `tradewiser` user can
#      run exactly `systemctl restart tradewiser` with no password. Nothing else.
#   3. Copies systemd/tradewiser-deploy.{service,timer} to /etc/systemd/system.
#   4. daemon-reload, enable, start the timer.
#   5. Runs one deploy immediately (so you see whether it works, not 2 min
#      from now via systemd).
#
# Uninstall:
#   sudo systemctl disable --now tradewiser-deploy.timer
#   sudo rm /etc/systemd/system/tradewiser-deploy.{service,timer}
#   sudo rm /etc/sudoers.d/tradewiser-deploy
#   sudo systemctl daemon-reload

set -euo pipefail

APP_DIR="${APP_DIR:-/opt/tradewiser}"
USER="${USER_OVERRIDE:-tradewiser}"
SERVICE="${SERVICE:-tradewiser}"

log()  { echo -e "\033[1;32m[pi-cd-install]\033[0m $*"; }
warn() { echo -e "\033[1;33m[pi-cd-install]\033[0m $*"; }
fail() { echo -e "\033[1;31m[pi-cd-install]\033[0m $*"; exit 1; }

# ── Preflight ────────────────────────────────────────────────────────────────

[[ $EUID -eq 0 ]] || fail "Run as root (sudo $0)"
[[ -d "$APP_DIR" ]] || fail "APP_DIR not found: $APP_DIR — is TradeWiser installed?"
[[ -d "$APP_DIR/.git" ]] || fail "$APP_DIR is not a git checkout (pull-based deploy needs git)"
id "$USER" >/dev/null 2>&1 || fail "user '$USER' does not exist"
systemctl status "$SERVICE" >/dev/null 2>&1 || \
    warn "service '$SERVICE' not currently active — install will proceed, but the deploy timer expects it"

# ── 1. Executable bit ────────────────────────────────────────────────────────

log "chmod +x $APP_DIR/scripts/pi-deploy.sh"
chmod +x "$APP_DIR/scripts/pi-deploy.sh"

# ── 2. Sudoers rule — narrow, single-command whitelist ───────────────────────

SUDOERS_FILE="/etc/sudoers.d/tradewiser-deploy"
# Resolve the FULL path to systemctl so the sudoers rule is exact (visudo
# rejects anything that looks like a wildcard).
SYSTEMCTL=$(command -v systemctl)

log "writing $SUDOERS_FILE (allows: $USER → $SYSTEMCTL restart $SERVICE, nopasswd)"
tmp=$(mktemp)
cat > "$tmp" <<EOF
# Auto-generated by pi-cd-install.sh — do not edit by hand.
# Purpose: let the pull-based deploy script (running as $USER) restart the
# trading service without a TTY password prompt. This whitelists EXACTLY
# one command; anything else the user tries with sudo still requires auth.
$USER ALL=(root) NOPASSWD: $SYSTEMCTL restart $SERVICE
EOF
# visudo -c validates syntax before we install; refuses on parse error.
visudo -c -f "$tmp" >/dev/null || { rm -f "$tmp"; fail "sudoers rule failed visudo -c"; }
install -m 0440 -o root -g root "$tmp" "$SUDOERS_FILE"
rm -f "$tmp"

# ── 3. systemd units ─────────────────────────────────────────────────────────

for u in tradewiser-deploy.service tradewiser-deploy.timer; do
    src="$APP_DIR/systemd/$u"
    dst="/etc/systemd/system/$u"
    [[ -f "$src" ]] || fail "missing $src (repo out of date?)"
    log "installing $dst"
    install -m 0644 -o root -g root "$src" "$dst"
done

# ── 4. Reload + enable + start ───────────────────────────────────────────────

log "systemctl daemon-reload"
systemctl daemon-reload

log "systemctl enable --now tradewiser-deploy.timer"
systemctl enable --now tradewiser-deploy.timer

# ── 5. First-run kick so the operator sees output immediately ────────────────

log "running one deploy pass now (output to journalctl)"
# Fire the service directly instead of waiting for the timer's OnBootSec=60s.
# This will no-op if the checkout is already up-to-date, or do a real deploy
# if origin/main has moved past HEAD.
systemctl start tradewiser-deploy.service || warn "first-run deploy exited non-zero — check: journalctl -u tradewiser-deploy -n 50"

# ── Report ───────────────────────────────────────────────────────────────────

log ""
log "  DONE  Auto-deploy is active."
log ""
log "  Timer status:    systemctl status tradewiser-deploy.timer"
log "  Live deploy log: journalctl -u tradewiser-deploy -f"
log "  Force deploy:    systemctl start tradewiser-deploy.service"
log "  Disable:         sudo systemctl disable --now tradewiser-deploy.timer"
log ""
log "  Optional overrides — write to /etc/tradewiser/deploy.env:"
log "     REQUIRE_GREEN_CI=0      # deploy without waiting for CI (danger)"
log "     HEALTH_TIMEOUT_SEC=60   # slower Pi? give restart more time"
log "     BRANCH=feature-x        # deploy from a branch other than main"
